apiVersion: v1
kind: Pod
metadata:
  name: mssql.cts.com
  labels:
    app: mssql
spec:
  containers:
  - name: mssqllinux
    image: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04
    ports:
    - name: mssql-port
      containerPort: 1433
    env:
      - name: ACCEPT_EULA
        value: Y
      - name: SA_PASSWORD
        value: Strong(!)Password
      - name: MSSQL_PID
        value: Express
