apiVersion: v1
kind: Pod
metadata:
  name: mssql.cts.com
  labels:
    app: mssql
spec:
  containers:
  - name: mssql_linux
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
    - name: nodejs-port
      containerPort: 1433
